import type { ServiceCategory, ServiceListItem } from "@/types/services";

export const serviceCategories: ServiceCategory[] = [
  "Plumbing",
  "Electrical",
  "Cleaning",
  "Landscaping",
  "IT Support",
  "Carpentry",
];

export const servicesData: ServiceListItem[] = [
  {
    id: "1",
    slug: "apex-plumbing-pros",
    companyName: "Apex Plumbing Pros",
    title: "Complete Home Plumbing & Pipe Repair",
    category: "Plumbing",
    description: "Fast and reliable plumbing repairs for homes and small businesses.",
    image: "/images/services/plumbing-1.jpg",
    rating: 4.9,
    reviews: 128,
    yearsExperience: 15,
    location: "Downtown Seattle, WA",
    priceFrom: 1000,
    priceUnit: "work",
    verified: true,
    availableNow: true,
    backgroundChecked: true,
    licensedInsured: true,
    acceptingNewClients: true,
    emergencyServices: true,
  },
  {
    id: "2",
    slug: "sparkle-and-shine",
    companyName: "Sparkle & Shine",
    title: "Eco-Friendly Deep House Cleaning",
    category: "Cleaning",
    description: "Eco-safe professional home cleaning services.",
    image: "/images/services/cleaning-1.jpg",
    rating: 4.8,
    reviews: 256,
    yearsExperience: 5,
    location: "Bellevue, WA",
    priceFrom: 2000,
    priceUnit: "visit",
    verified: true,
    availableNow: true,
    backgroundChecked: true,
    licensedInsured: false,
    acceptingNewClients: true,
    emergencyServices: false,
  },
  {
    id: "3",
    slug: "volt-masters-inc",
    companyName: "Volt Masters Inc.",
    title: "Electrical Panel Upgrade & Wiring",
    category: "Electrical",
    description: "Certified electrical upgrades and residential wiring services.",
    image: "/images/services/electrical-1.jpg",
    rating: 5.0,
    reviews: 89,
    yearsExperience: 20,
    location: "Redmond, WA",
    priceFrom: 5000,
    priceUnit: "hour",
    verified: true,
    availableNow: false,
    backgroundChecked: true,
    licensedInsured: true,
    acceptingNewClients: false,
    emergencyServices: true,
  },
  {
    id: "4",
    slug: "green-thumb-gardens",
    companyName: "Green Thumb Gardens",
    title: "Landscape Design & Lawn Maintenance",
    category: "Landscaping",
    description: "Residential landscaping, lawn care and garden maintenance.",
    image: "/images/services/landscaping-1.jpg",
    rating: 4.7,
    reviews: 312,
    yearsExperience: 10,
    location: "Kirkland, WA",
    priceFrom: 1500,
    priceUnit: "hour",
    verified: false,
    availableNow: true,
    backgroundChecked: true,
    licensedInsured: false,
    acceptingNewClients: true,
    emergencyServices: false,
  },
  {
    id: "5",
    slug: "tech-wizards",
    companyName: "Tech Wizards",
    title: "IT Support & Network Installation",
    category: "IT Support",
    description: "On-site and remote IT support for homes and businesses.",
    image: "/images/services/it-1.jpg",
    rating: 4.9,
    reviews: 445,
    yearsExperience: 8,
    location: "Seattle, WA (Remote Avail.)",
    priceFrom: 2500,
    priceUnit: "hour",
    verified: true,
    availableNow: true,
    backgroundChecked: true,
    licensedInsured: true,
    acceptingNewClients: true,
    emergencyServices: true,
  },
  {
    id: "6",
    slug: "woodcrafters-studio",
    companyName: "WoodCrafters Studio",
    title: "Custom Carpentry & Cabinetry",
    category: "Carpentry",
    description: "Custom woodwork, cabinetry and finish carpentry.",
    image: "/images/services/carpentry-1.jpg",
    rating: 4.8,
    reviews: 156,
    yearsExperience: 25,
    location: "Tacoma, WA",
    priceFrom: 1200,
    priceUnit: "hour",
    verified: true,
    availableNow: true,
    backgroundChecked: false,
    licensedInsured: true,
    acceptingNewClients: true,
    emergencyServices: false,
  },
];